name: sharding-repl-cache
services:
  mongodb1:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: mongodb1
    restart: always
    ports:
      - "27016:27016"
    volumes:
      - mongodb1_data_container:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.14
    depends_on:
      - shard1
    command:
      [
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27016"
      ] #команда для создания реплики
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongodb2:
    container_name: mongodb2
    image: dh-mirror.gitverse.ru/mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb2_data_container:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.13
    depends_on:
      - shard2
    command:
      [
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27017"
      ] #команда для создания реплики
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongodb3:
    container_name: mongodb3
    image: dh-mirror.gitverse.ru/mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongodb3_data_container:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.12
    depends_on:
      - shard2
    command:
      [
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27018"
      ] #команда для создания реплики
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongodb4:
    container_name: mongodb4
    image: dh-mirror.gitverse.ru/mongo:latest
    ports:
      - "27019:27019"
    volumes:
      - mongodb4_data_container:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.11
    depends_on:
      - shard2
    command:
      [
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ] #команда для создания реплики
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo_api2:
    container_name: pymongo_api2
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    networks:
      app-network:
        ipv4_address: 173.17.0.6
    depends_on:
      - redis_1
      - mongos_router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27023"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis_1:6379"

  configSrv:
    image: mongo:latest # docker образ
    container_name: configSrv
    restart: always
    ports:
      - "27020:27020"
    volumes:
      - config-data:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1:
    image: mongo:latest
    container_name: shard1
    restart: always
    ports:
      - "27021:27021"
    volumes:
      - shard1-data:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27021"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2:
    image: mongo:latest
    container_name: shard2
    restart: always
    ports:
      - "27022:27022"
    volumes:
      - shard2-data:/data/db
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27022"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27023:27023"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv:27020",
        "--bind_ip_all",
        "--port",
        "27023"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  redis_1:
    image: "redis:latest"
    container_name: redis_1
    ports:
      - "6379"
    volumes:
      - redis_1:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.0.5

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  redis_1:
  mongodb1_data_container:
  mongodb2_data_container:
  mongodb3_data_container:
  mongodb4_data_container:
  config-data:
  shard1-data:
  shard2-data:
